version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
      - image: hqml:1.0.0
    steps:
      - checkout
      - run: python hqml.py update
      - run: chmod 777 hqml
      - run: sudo ln -s `pwd`/hqml /usr/bin/hqml
  test:
    docker:
      - image: circleci/python:3.8.0
      - image: hqml:1.0.0
    steps:
      - checkout
      - run: mkdir test && cd test
      - run: hqml create .
      - run: hqml build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        requires:
          - build