version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run: python hqml update
      - run: pip install -r qmlcore/requirements.txt
      - run: chmod 777 hqml
      - run: sudo ln -s `pwd`/hqml /usr/bin/hqml
      - run: mkdir test && cd test
      - run: hqml create .
      - run: hqml build
workflows:
  version: 2
  build_and_test:
    jobs:
      - test